name: "Build & Test"

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Update submodules
      run: git submodule init && git submodule update
    - run: |
        npm install
        npm run all
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
      fail-fast: false
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - uses: ./
    - name: NativeScript Doctor
      run: ns doctor
